version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mxshop_user_srv_mysql-peewee
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mxshop_user_srv
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: