//
// Copyright 2023 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//这个文件是一个 Protocol Buffers (protobuf) 定义文件，它定义了数据的结构化格式，
//用于在不同系统和不同编程语言间进行高效的数据交换。
// 代码生成：通过 protoc 编译器可以自动生成多种语言的代码
//protoc -I . hello_proto.proto --go_out=plugins=grpc:. 生成 go 代码

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: hello_proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Teacher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Teacher) Reset() {
	*x = Teacher{}
	mi := &file_hello_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Teacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teacher) ProtoMessage() {}

func (x *Teacher) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teacher.ProtoReflect.Descriptor instead.
func (*Teacher) Descriptor() ([]byte, []int) {
	return file_hello_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Teacher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Teacher) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Teacher) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Teacher) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_hello_proto_proto protoreflect.FileDescriptor

const file_hello_proto_proto_rawDesc = "" +
	"\n" +
	"\x11hello_proto.proto\"_\n" +
	"\aTeacher\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05emailB\tZ\a.;protob\x06proto3"

var (
	file_hello_proto_proto_rawDescOnce sync.Once
	file_hello_proto_proto_rawDescData []byte
)

func file_hello_proto_proto_rawDescGZIP() []byte {
	file_hello_proto_proto_rawDescOnce.Do(func() {
		file_hello_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hello_proto_proto_rawDesc), len(file_hello_proto_proto_rawDesc)))
	})
	return file_hello_proto_proto_rawDescData
}

var file_hello_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hello_proto_proto_goTypes = []any{
	(*Teacher)(nil), // 0: Teacher
}
var file_hello_proto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_proto_proto_init() }
func file_hello_proto_proto_init() {
	if File_hello_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_proto_proto_rawDesc), len(file_hello_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hello_proto_proto_goTypes,
		DependencyIndexes: file_hello_proto_proto_depIdxs,
		MessageInfos:      file_hello_proto_proto_msgTypes,
	}.Build()
	File_hello_proto_proto = out.File
	file_hello_proto_proto_goTypes = nil
	file_hello_proto_proto_depIdxs = nil
}
